services:
  db:
    image: postgres
    container_name: postgres
    volumes: 
      - rebase-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    networks:
      - base

  app:
    image: ruby
    container_name: app
    command: bash -c "bundle install && ruby server.rb"
    ports:
      - 3000:3000
    depends_on:
      - db
      - sidekiq
    working_dir: /app
    networks:
      - base
    volumes:
      - ./:/app
      - gems:/usr/local/bundle
    environment:
      REDIS_URL: redis://redis:6379

  redis:
    image: redis
    container_name: redis
    networks:
      - base

  sidekiq:
    image: ruby
    container_name: sidekiq
    command: bash -c "bundle install && bundle exec sidekiq -r './data_worker.rb'"
    working_dir: /app
    networks:
      - base
    volumes:
      - ./:/app
      - gems:/usr/local/bundle
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379

  
networks:
  base:
volumes:
  gems:
  rebase-db: